export const users = [
  {
    id: "usr-inspector-01",
    username: "inspector",
    password: "login2026",
    name: "Claudio Perez",
    role: "inspector",
    title: "Inspector municipal",
    profile: {
      personal: {
        rut: "16.458.223-1",
        email: "claudio.perez@seguridadmunicipal.cl",
        phone: "+56 9 6123 4455",
        emergencyContact: "Ana Perez - +56 9 7788 1122",
      },
      municipal: {
        municipality: "Direccion de Seguridad Municipal",
        unit: "Fiscalizacion Territorial",
        badgeId: "ISM-214",
        shift: "Turno tarde 14:00 - 22:00",
        sector: "Santiago Centro y barrios comerciales",
        supervisor: "Luis Torres",
      },
      platform: {
        appRole: "Inspector en terreno",
        accessLevel: "Creacion de casos, evidencia y actas",
        device: "iPhone operativo municipal",
        appVersion: "v1.6.2",
        syncStatus: "Sincronizacion automatica habilitada",
        signatureStatus: "Firma digital simple activa",
      },
      shifts: [
        {
          id: "turno-01",
          name: "Turno diurno de fiscalizacion comercial",
          days: "Lunes y martes",
          hours: "08:00 a 16:00",
          checkpoint: "Base operativa Santiago Centro",
          routes: [
            "Ruta A: Paseo Ahumada - Plaza de Armas - Catedral",
            "Ruta B: San Antonio - Monjitas - Mercado Central",
            "Ruta C: Alameda - Estado - San Diego",
          ],
        },
        {
          id: "turno-02",
          name: "Turno tarde de control territorial",
          days: "Miercoles y jueves",
          hours: "14:00 a 22:00",
          checkpoint: "Subcentral Barrio Franklin",
          routes: [
            "Ruta D: Franklin - Biobio - San Diego sur",
            "Ruta E: Avenida Matta - Santa Rosa - Diez de Julio",
            "Ruta F: Portugal - Santa Isabel - Vicuña Mackenna",
          ],
        },
        {
          id: "turno-03",
          name: "Turno nocturno preventivo",
          days: "Viernes",
          hours: "18:00 a 02:00",
          checkpoint: "Subcentral Barrio Lastarria",
          routes: [
            "Ruta G: Lastarria - Bellas Artes - Parque Forestal",
            "Ruta H: Bellavista - Pio Nono - Patronato",
            "Ruta I: Plaza Baquedano - Bustamante - Parque San Borja",
          ],
        },
        {
          id: "turno-04",
          name: "Cobertura fin de semana y ferias",
          days: "Sabado y domingo",
          hours: "09:00 a 17:00",
          checkpoint: "Punto fijo Estacion Central",
          routes: [
            "Ruta J: Terminal Sur - Exposicion - Ecuador",
            "Ruta K: Meiggs - Union Latinoamericana - Matucana",
            "Ruta L: Feria local - plazas - ejes residenciales con incivilidades",
          ],
        },
      ],
    },
  },
  {
    id: "usr-supervisor-01",
    username: "supervisor",
    password: "login2026",
    name: "Luis Torres",
    role: "supervisor",
    title: "Supervisor de fiscalizacion",
    profile: {
      personal: {
        rut: "14.102.887-6",
        email: "luis.torres@seguridadmunicipal.cl",
        phone: "+56 9 5234 9901",
        emergencyContact: "Mesa de turno - +56 2 2444 0190",
      },
      municipal: {
        municipality: "Direccion de Seguridad Municipal",
        unit: "Coordinacion de Fiscalizacion",
        badgeId: "SUP-031",
        shift: "Turno administrativo 08:30 - 18:00",
        sector: "Cobertura comunal",
        supervisor: "Administracion central",
      },
      platform: {
        appRole: "Supervisor operativo",
        accessLevel: "Dashboard, revision de casos y control operacional",
        device: "Notebook de supervision",
        appVersion: "v1.6.2",
        syncStatus: "Monitoreo de flota y cola offline",
        signatureStatus: "Validacion de actas habilitada",
      },
    },
  },
];

export const dashboard = {
  metrics: {
    activeCases: 148,
    activeCasesNote: "+12 hoy",
    recordsIssued: 92,
    recordsIssuedNote: "84% con firma digital",
    averageResponseTime: "23 min",
    averageResponseTimeNote: "Desde inspeccion a cierre parcial",
    pendingOffline: 6,
    pendingOfflineNote: "Ultima sincronizacion hace 4 min",
  },
  sync: {
    onlineDevices: 18,
    offlineQueue: 6,
  },
  heatmap: ["high", "mid", "low", "mid", "high", "low", "mid", "high", "low"],
  evidenceChannels: [
    "Fotos georreferenciadas con sello de fecha y hora",
    "Video de procedimientos y hallazgos",
    "Audio para ruidos molestos y descargos",
    "Formularios dinamicos por tipo de infraccion",
    "Firma digital del inspector y fiscalizado",
    "Actas PDF con folio unico y QR verificable",
  ],
};

export const categories = [
  {
    slug: "ruidos",
    name: "Ruidos molestos",
    description: "Registro con audio, horario, direccion y reincidencia.",
  },
  {
    slug: "ambulante",
    name: "Comercio ambulante",
    description: "Control de operativos, decomisos y evidencia fotografica.",
  },
  {
    slug: "via-publica",
    name: "Danos via publica",
    description: "Levantamiento de danos con georreferenciacion y derivacion.",
  },
  {
    slug: "vehiculos",
    name: "Vehiculos abandonados",
    description: "Patente, estado visual, dias observados y acta QR.",
  },
  {
    slug: "luminarias",
    name: "Luminarias",
    description: "Control de fallas por sector, poste y criticidad.",
  },
  {
    slug: "incivilidades",
    name: "Incivilidades",
    description: "Conductas incivicas con evidencia y bitacora territorial.",
  },
  {
    slug: "transito",
    name: "Transito",
    description: "Fiscalizacion de infracciones, patentes y horarios.",
  },
  {
    slug: "basura",
    name: "Basura ilegal",
    description: "Microbasurales, volumen, tipo de residuo y seguimiento.",
  },
];

export const cases = [
  {
    id: "FM-2026-00184",
    type: "Ruidos molestos",
    category: "ruidos",
    priority: "high",
    status: "En revision",
    zone: "Santiago Centro",
    address: "San Diego 1450",
    inspector: "Claudio Perez",
    channel: "audio",
    mode: "online",
    source: "camera",
    summary: "Denuncia nocturna por musica amplificada en local comercial.",
    evidence: "2 fotos, 1 audio, GPS, firma inspector",
    acta: "Acta QR emitida y pendiente de validacion",
    location: {
      latitude: -33.45694,
      longitude: -70.64827,
      accuracy: 12,
      capturedAt: "2026-05-14T21:44:00.000Z",
    },
  },
  {
    id: "FM-2026-00181",
    type: "Basura ilegal",
    category: "basura",
    priority: "medium",
    status: "Derivado a operaciones",
    zone: "Maipu",
    address: "Camino Rinconada 2190",
    inspector: "Marco Silva",
    channel: "video",
    mode: "offline",
    source: "camera",
    summary: "Microbasural detectado en sitio eriazo con evidencia audiovisual.",
    evidence: "4 fotos, 1 video, GPS",
    acta: "Acta preliminar sincronizada parcialmente",
    location: {
      latitude: -33.50952,
      longitude: -70.76118,
      accuracy: 19,
      capturedAt: "2026-05-14T20:15:00.000Z",
    },
  },
  {
    id: "FM-2026-00176",
    type: "Vehiculo abandonado",
    category: "vehiculos",
    priority: "low",
    status: "Programado",
    zone: "Quinta Normal",
    address: "Mapocho 886",
    inspector: "Paula Torres",
    channel: "foto",
    mode: "online",
    source: "gallery",
    summary: "Vehiculo sin movimiento por mas de 15 dias en via publica.",
    evidence: "3 fotos, patente, GPS, formulario",
    acta: "Pendiente de notificacion en terreno",
    location: {
      latitude: -33.42973,
      longitude: -70.69814,
      accuracy: 10,
      capturedAt: "2026-05-14T18:03:00.000Z",
    },
  },
  {
    id: "FM-2026-00169",
    type: "Comercio ambulante",
    category: "ambulante",
    priority: "high",
    status: "Cierre juridico",
    zone: "Estacion Central",
    address: "Alameda 4012",
    inspector: "Javier Fuentes",
    channel: "foto",
    mode: "offline",
    source: "camera",
    summary: "Operativo de despeje en eje comercial con decomiso registrado.",
    evidence: "6 fotos, 1 video, firma doble, QR",
    acta: "Acta firmada y lista para expediente",
    location: {
      latitude: -33.45611,
      longitude: -70.67862,
      accuracy: 16,
      capturedAt: "2026-05-14T17:22:00.000Z",
    },
  },
];
