export const users = [
  {
    id: "usr-inspector-01",
    username: "inspector",
    password: "1234",
    name: "Carla Rojas",
    role: "inspector",
    title: "Inspector municipal",
  },
  {
    id: "usr-supervisor-01",
    username: "supervisor",
    password: "1234",
    name: "Rodrigo Mella",
    role: "supervisor",
    title: "Supervisor de fiscalizacion",
  },
];

export const dashboard = {
  metrics: {
    activeCases: 148,
    activeCasesNote: "+12 hoy",
    recordsIssued: 92,
    recordsIssuedNote: "84% con firma digital",
    averageResponseTime: "23 min",
    averageResponseTimeNote: "Desde inspeccion a cierre parcial",
    pendingOffline: 6,
    pendingOfflineNote: "Ultima sincronizacion hace 4 min",
  },
  sync: {
    onlineDevices: 18,
    offlineQueue: 6,
  },
  heatmap: ["high", "mid", "low", "mid", "high", "low", "mid", "high", "low"],
  evidenceChannels: [
    "Fotos georreferenciadas con sello de fecha y hora",
    "Video de procedimientos y hallazgos",
    "Audio para ruidos molestos y descargos",
    "Formularios dinamicos por tipo de infraccion",
    "Firma digital del inspector y fiscalizado",
    "Actas PDF con folio unico y QR verificable",
  ],
};

export const categories = [
  {
    slug: "ruidos",
    name: "Ruidos molestos",
    description: "Registro con audio, horario, direccion y reincidencia.",
  },
  {
    slug: "ambulante",
    name: "Comercio ambulante",
    description: "Control de operativos, decomisos y evidencia fotografica.",
  },
  {
    slug: "via-publica",
    name: "Danos via publica",
    description: "Levantamiento de danos con georreferenciacion y derivacion.",
  },
  {
    slug: "vehiculos",
    name: "Vehiculos abandonados",
    description: "Patente, estado visual, dias observados y acta QR.",
  },
  {
    slug: "luminarias",
    name: "Luminarias",
    description: "Control de fallas por sector, poste y criticidad.",
  },
  {
    slug: "incivilidades",
    name: "Incivilidades",
    description: "Conductas incivicas con evidencia y bitacora territorial.",
  },
  {
    slug: "transito",
    name: "Transito",
    description: "Fiscalizacion de infracciones, patentes y horarios.",
  },
  {
    slug: "basura",
    name: "Basura ilegal",
    description: "Microbasurales, volumen, tipo de residuo y seguimiento.",
  },
];

export const cases = [
  {
    id: "FM-2026-00184",
    type: "Ruidos molestos",
    category: "ruidos",
    priority: "high",
    status: "En revision",
    zone: "Santiago Centro",
    address: "San Diego 1450",
    inspector: "Carla Rojas",
    channel: "audio",
    mode: "online",
    source: "camera",
    summary: "Denuncia nocturna por musica amplificada en local comercial.",
    evidence: "2 fotos, 1 audio, GPS, firma inspector",
    acta: "Acta QR emitida y pendiente de validacion",
    location: {
      latitude: -33.45694,
      longitude: -70.64827,
      accuracy: 12,
      capturedAt: "2026-05-14T21:44:00.000Z",
    },
  },
  {
    id: "FM-2026-00181",
    type: "Basura ilegal",
    category: "basura",
    priority: "medium",
    status: "Derivado a operaciones",
    zone: "Maipu",
    address: "Camino Rinconada 2190",
    inspector: "Marco Silva",
    channel: "video",
    mode: "offline",
    source: "camera",
    summary: "Microbasural detectado en sitio eriazo con evidencia audiovisual.",
    evidence: "4 fotos, 1 video, GPS",
    acta: "Acta preliminar sincronizada parcialmente",
    location: {
      latitude: -33.50952,
      longitude: -70.76118,
      accuracy: 19,
      capturedAt: "2026-05-14T20:15:00.000Z",
    },
  },
  {
    id: "FM-2026-00176",
    type: "Vehiculo abandonado",
    category: "vehiculos",
    priority: "low",
    status: "Programado",
    zone: "Quinta Normal",
    address: "Mapocho 886",
    inspector: "Paula Torres",
    channel: "foto",
    mode: "online",
    source: "gallery",
    summary: "Vehiculo sin movimiento por mas de 15 dias en via publica.",
    evidence: "3 fotos, patente, GPS, formulario",
    acta: "Pendiente de notificacion en terreno",
    location: {
      latitude: -33.42973,
      longitude: -70.69814,
      accuracy: 10,
      capturedAt: "2026-05-14T18:03:00.000Z",
    },
  },
  {
    id: "FM-2026-00169",
    type: "Comercio ambulante",
    category: "ambulante",
    priority: "high",
    status: "Cierre juridico",
    zone: "Estacion Central",
    address: "Alameda 4012",
    inspector: "Javier Fuentes",
    channel: "foto",
    mode: "offline",
    source: "camera",
    summary: "Operativo de despeje en eje comercial con decomiso registrado.",
    evidence: "6 fotos, 1 video, firma doble, QR",
    acta: "Acta firmada y lista para expediente",
    location: {
      latitude: -33.45611,
      longitude: -70.67862,
      accuracy: 16,
      capturedAt: "2026-05-14T17:22:00.000Z",
    },
  },
];
